name: hello world
on: pull_request
jobs:
    check_dns_misconfigs:
        runs-on: ubuntu-latest
        steps:
          - name: Hello world
            run: |
                echo "Hello, ${{ github.actor }}"
                echo "Rep: ${{ github.repository }}"
                echo "Ref base: ${{ github.base_ref }}"
                echo "Ref: ${{ github.ref }}"
                echo "Ref name: ${{ github.ref_name }}"
